#!/bin/sh

pkill -x sxhkd
sxhkd -m -1 & # the `-m -1` handles newly connected keyboards

bspc config border_width               1
bspc config window_gap                 0

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_by_distance          true
bspc config history_aware_focus        true
bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Claws-mail desktop=^3
bspc rule -a rdesktop desktop=^4 state=floating
bspc rule -a Nitrogen state=pseudo_tiled
bspc rule -a Blueman-manager state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a 'Page Unresponsive' state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Xmessage state=floating

# re-parent existing windows into the current session
if [ -e "$BSPWM_STATE" ]; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
else
	bspc wm --adopt-orphans
fi

bspwm-panel &
