#!/bin/sh

bspc config border_width               2
bspc config window_gap                 12

bspc config split_ratio                0.52
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_by_distance          true
bspc config history_aware_focus        true
bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 a

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# restore windows into current session
. ~/.config/bspwm/examples/loop/profile
. ~/.config/bspwm/examples/loop/bspwmrc

bspwm-panel &
sxhkd -m -1 & # the -1 ensures new keyboards are mapped
